# ⚠️  Replace placeholder values with real base64-encoded secrets before applying.
#     Encode with:  echo -n "your-value" | base64
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-search-secrets
  namespace: mongodb-search
  labels:
    app.kubernetes.io/part-of: mongodb-search
type: Opaque
data:
  # MongoDB Atlas connection string
  MONGODB_URI: "REPLACE_WITH_BASE64_ENCODED_VALUE"
  # VoyageAI embedding API key
  VOYAGE_API_KEY: "REPLACE_WITH_BASE64_ENCODED_VALUE"
  # MinIO / S3 credentials
  AWS_ACCESS_KEY_ID: "YWRtaW4="            # admin
  AWS_SECRET_ACCESS_KEY: "YWRtaW4xMjM0NQ==" # admin12345
  # Jina reranker (optional)
  # JINA_API_KEY: "REPLACE_WITH_BASE64_ENCODED_VALUE"
